2023-03-05 09:56:05,045 ERROR test
Traceback (most recent call last):
  File "C:\Users\kevin\PycharmProjects\Super_Mario_Bros_The_Movie_The_Game\game.py", line 9, in <module>
    raise Exception("test")
Exception: test
